config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles, only: [:new, :create]
  resources :tweets do
    resources :comments, only: [:create]
  end
  root 'articles#index'
  get 'info' => 'top#info'
  get 'profile' => 'top#profile'
  resources :users, only: [:show] do
    resources :wants, only: [:new, :create]
  end
end


# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
#                   Prefix Verb   URI Pattern                          Controller#Action
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#        user_registration POST   /users(.:format)                     devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#                          PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#                 articles POST   /articles(.:format)                  articles#create
#              new_article GET    /articles/new(.:format)              articles#new
#           tweet_comments POST   /tweets/:tweet_id/comments(.:format) comments#create
#                   tweets GET    /tweets(.:format)                    tweets#index
#                          POST   /tweets(.:format)                    tweets#create
#                new_tweet GET    /tweets/new(.:format)                tweets#new
#               edit_tweet GET    /tweets/:id/edit(.:format)           tweets#edit
#                    tweet GET    /tweets/:id(.:format)                tweets#show
#                          PATCH  /tweets/:id(.:format)                tweets#update
#                          PUT    /tweets/:id(.:format)                tweets#update
#                          DELETE /tweets/:id(.:format)                tweets#destroy
#                     root GET    /                                    articles#index
#                     info GET    /info(.:format)                      top#info
#                  profile GET    /profile(.:format)                   top#profile
#               user_wants POST   /users/:user_id/wants(.:format)      wants#create
#            new_user_want GET    /users/:user_id/wants/new(.:format)  wants#new
#                     user GET    /users/:id(.:format)                 users#show
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet               #tweetsテーブルとのアソシエーション
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :comments
  has_many :wants
end

app/models/want.rb
class Want < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @articles = Article.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
  end

  def create
    Article.create(article_params)
  end

  private
  def article_params
    params.permit(:title, :image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def info
  end

  def profile
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.permit(:image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/controllers/wants_controller.rb
class WantsController < ApplicationController

  def new
  end

  def create
    Want.create(title: want_params[:title], rate: want_params[:rate], text: want_params[:text], user_id: current_user.id)
  end

  private
  def want_params
    params.permit(:title, :rate, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/articles/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/articles/index.html.erb
  <div class="contents row" >
    <% @articles.each do |article| %>
      <p><%= article.title %></p>
      <img class="content_post" src="<%= article.image %>"></img>
      <p><%= article.text %></p>
    <% end %>
    <%= paginate(@articles) %>
  </div>

app/views/articles/new.html.erb
<div class="contents row">
  <%= form_tag('/articles', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <input placeholder="Title" type="text" name="title">
    <input placeholder="Image Url" type="text" name="image">
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BSファンサイトトップページ！！</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">BSファンサイトトップページ！！</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/">NEWS</a>
          <a class="get" href="/info">作品情報</a>
          <a class="get" href="/profile">プロフィール</a>
          <a class="post" href="/tweets">SNS</a>
          <a class="post" href="/articles/new">グッズ</a>
          <a class="post" href="/articles/new">ゲーム</a>
          <a class="post" href="/articles/new">イラストギャラリー</a>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <a href="/users/<%= current_user.id %>">your baby-steps</a>
                  <a href="/users/<%= current_user.id %>">マイページ</a>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <a class="post" href="/articles/new">【NEWS】記事を投稿する</a>
            <a class="post" href="/tweets/new">【SNS】達成POSTを投稿する</a>
            <a class="get" href="/users/<%=:user_id %>/wants/new">【SNS】ベイビーステップを始める</a>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright BS.
      </p>
    </footer>
  </body>
</html>

app/views/top/info.html.erb
<p>几帳面で真面目な男子高校生・丸尾栄一郎が、高校入学を機にテニスの魅力に目覚め、テニス選手として成長していく青春ドラマ[2]。神奈川県藤沢市が主なモデルとなっている。
作者の勝木光はテニス経験者であり、本作は綿密な取材に基づいて現実的な技術や戦術、トレーニング理論が描かれている。男子シングルスをメインに扱っており、ダブルスはほとんど描かれていない。
タイトルの英語表記は「Baby Steps」となっているが、日本語表記では最後に「ス」はつかない。
2014年4月から9月までテレビアニメ第1シリーズが、2015年4月から9月まで第2シリーズが放送された。</p>

app/views/top/profile.html.erb
  <p>
勝木 光（かつき ひかる）は、日本の漫画家。女性。代表作は『ベイビーステップ』

勝木鮎美名義で描いた『ダチョウの空』が第68回週刊少年マガジン新人漫画賞で入選。2002年、同作品が『マガジンFRESH』に掲載され、デビューを果たす。
2007年より現在の名義に改め、『週刊少年マガジン』にて『ベイビーステップ』の連載を開始、2014年に同作で講談社漫画賞少年部門受賞。
  </p>

app/views/tweets/_tweet.html.erb
<div>
  <a href="">
    <span>投稿者</span><%= tweet.user.nickname %>
  </a>
    <ul class="more_list">
        <li>
          <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
        </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  <img class="content_post" src="<%= tweet.image %>"></img>
  <p><%= tweet.text %></p>
</div>

app/views/tweets/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tweets">みんなのPOST一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
  <div class="contents row">
    <%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
      <h3>
        編集する
      </h3>
      <input placeholder="Image Url" type="text" name="image" value="<%= @tweet.image %>" autofocus="true">
      <textarea cols="30" name="text" placeholder="Comment" rows="10"><%= @tweet.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

app/views/tweets/index.html.erb
  <div class="contents row" >
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweet", locals: { tweet: tweet } %>
    <% end %>
    <%= paginate(@tweets) %>
  </div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweets', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <input placeholder="Image Url" type="text" name="image">
      <textarea cols="30" name="text" placeholder="Comment" rows="10"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <div>
          <ul class="more_list">
            <li>
              <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
            </li>
          </ul>
        </div>
        <img class="content_post" src="<%= @tweet.image %>"></img>
        <p><%= @tweet.text %></p>
    <% else %>
        <img class="content_post" src="<%= @tweet.image %>"></img>
        <p><%= @tweet.text %></p>
    <% end %>
    <span class="name">
      <a href=""> <!-- /users/<%= @tweet.user.id %> -->
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="contents row" >
    <p><%= @nickname %>さんのこれまでのベイビーステップ</p>
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
    <% end %>
    <%= paginate(@tweets) %>
  </div>

app/views/wants/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        では次はこの「やりたいこと」の中で一番「やりたい」想いが強いものを一つ選びましょう！！
      </h3>
      <a class="btn" href="/tweets">みんなのPOST一覧へ戻る</a>
    </div>
  </div>

app/views/wants/new.html.erb
<h1>企画の説明</h1>
    <div class="container">
      <%= form_tag('/users/:user_id/wants', method: :post) do %>
        <h3>
          「やりたいこと」を思う存分入力してみよう！！
        </h3>
        <input placeholder="Title" type="text" name="title">
        <input placeholder="Rate" type="text" name="rate">
        <textarea cols="30" name="text" placeholder="Text" rows="10"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    </div>